### PR TITLE
Fix conflict detection logic

### LINKED ISSUE #52: Wrong remind about conflicts
https://github.com/go-gitea/gitea/pull/24277#issuecomment-1519008991

### PR DESCRIPTION
**Pull request by yardenshoham**
- Mention author
- Fix comment log
- Fix merge conflict detection (missed `break`), fixes #52

### CODE REVIEW

File: src/mergeQueue.ts [hunk 1]
```diff
@@ -10,19 +10,22 @@ export const run = async () => {
...
+    prs.push(pr);
     milestoneToPr.set(milestone, prs);
   }
 
   // for each milestone, try to update the lowest PR number (only if it needs an update), if it fails, try the next one
   for (const [_, prs] of milestoneToPr) {
     for (const pr of prs) {
-      if (!await needsUpdate(pr)) break;
-      const response = await updatePr(pr);
+      if (!await needsUpdate(pr.number)) break;
```
Comment (silverwind) [inline src/mergeQueue.ts:27]: Shouldn't typescript prevent these class of error, e.g. calling a function with incorrect arguments? :)

Comment (yardenshoham) [reply src/mergeQueue.ts:27]: I changed PR from a number to an object in this change. To keep the author information

**Comment by yardenshoham** [comment]
It's basically 3 PRs in one, review each commit differently

File: src/mergeQueue.ts (hunk 1 above)
Comment (silverwind) [reply src/mergeQueue.ts:27]: ah, yes

**Review by silverwind — APPROVED** [review]

File: src/mergeQueue.ts [hunk 2]
```diff
@@ -10,19 +10,22 @@ export const run = async () => {
   const pendingMerge = await fetchPendingMerge();
 
   // group PRs by milestone
-  const milestoneToPr = new Map<string, number[]>();
+  const milestoneToPr = new Map<
+    string,
+    { number: number; user: { login: string } }[]
```
Comment (delvh) [inline src/mergeQueue.ts:15]: What about `name` instead of `login`?
I had to look below to find out that you mean the name, and not some type of secret or authentication method…

Comment (delvh) [reply src/mergeQueue.ts:15]: Ah wait, does it come like that from the GitHub API?
If yes, ignore my comment.

Comment (delvh) [reply src/mergeQueue.ts:15]: If no, then why do you not assign the user manually?

Comment (yardenshoham) [reply src/mergeQueue.ts:15]: it's from the GitHub API
